-- AlterTable
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "storyPoints" INTEGER;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "startedAt" TIMESTAMP(3);
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "completedAt" TIMESTAMP(3);
